### ISSUE TITLE
Internal mod Star crashing players in Bumblezone

### ISSUE THREAD

**Issue by TelepathicGrunt** [Alpha-s-Stuff/TinkersConstruct#131]
### Minecraft Version

1.20.1

### Fabric Version

N/A

### Fabric API Version

0.92.1+1.20.1

### Hephaestus Version

1.20.1-3.6.4.273

### Describe your issue

Players are non stop reporting to me thinking my mod is broken when it is the broken mixin in Star that Hephaestus includes. 
![image](https://github.com/Alpha-s-Stuff/TinkersConstruct/assets/40846040/32186ebd-6a38-4a13-9023-19baad1cbe72)

https://github.com/TelepathicGrunt/Bumblezone/issues/390
https://github.com/TelepathicGrunt/Bumblezone/issues/389
https://github.com/TelepathicGrunt/Bumblezone/issues/385

Please update Hephaestus and have AoF include the fix so I stop getting non-stop bug reports for something outside my control. Please.

### Other mods

Bumblezone

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

Sodium

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by flarefluffsune** [comment]
I'm having this issue too, here's my log: https://paste.ee/p/9gg5m
Edit: I should say I'm playing All of Fabric 7

```
Time: 2024-05-22 09:27:06
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3610.method_15772()" because the return value of "net.minecraft.class_1309.getTouchingFluid()" is null
	at net.minecraft.class_1309.handler$mea000$star$checkIfCustomFluidIsBreathable(class_1309.java:3165)
	at net.minecraft.class_1309.method_6094(class_1309.java:347)
	at net.minecraft.class_1309.handler$mok000$the_bumblezone$bumblezone$breathing(class_1309.java:15676)
	at net.minecraft.class_1309.method_5670(class_1309.java:467)
	at net.minecraft.class_1308.method_5670(class_1308.java:284)
	at net.minecraft.class_1297.method_5773(class_1297.java:474)
	at net.minecraft.class_1309.method_5773(class_1309.java:2380)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_4466.method_5773(class_4466.java:299)
	at net.minecraft.class_3218.observable$track(class_3218.java:22254)
	at net.minecraft.class_3218.redirect$ipd000$observable$onTickNonPassenger(class_3218.java:22270)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by AlphaMode** [comment]
I believe this was fixed a few releases ago
