### ISSUE TITLE
Hephaestus's "Chests" cannot be opened

### ISSUE THREAD

**Issue by unilock** [Alpha-s-Stuff/TinkersConstruct#83]
### Minecraft Version

1.20.1

### Fabric Version

0.14.23

### Fabric API Version

0.90.4+1.20.1

### Hephaestus Version

1.20.1-3.6.3.232

### Describe your issue

When attempting to open Hephaestus' "Cast Chest", "Part Chest", or "Tinker's Chest", an error is instead printed to the log:

```
[08:56:48] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@7a8a6057, suppressing error
java.lang.ClassCastException: class slimeknights.mantle.transfer.item.ItemHandlerStorage cannot be cast to class net.fabricmc.fabric.api.transfer.v1.storage.SlottedStorage (slimeknights.mantle.transfer.item.ItemHandlerStorage and net.fabricmc.fabric.api.transfer.v1.storage.SlottedStorage are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4a9e6faf)
	at slimeknights.tconstruct.tables.menu.module.SideInventoryContainer.<init>(SideInventoryContainer.java:38) ~[Hephaestus-1.20.1-3.6.3.232.jar:?]
	at slimeknights.tconstruct.tables.menu.module.SideInventoryContainer.<init>(SideInventoryContainer.java:28) ~[Hephaestus-1.20.1-3.6.3.232.jar:?]
	at slimeknights.tconstruct.tables.menu.TinkerChestContainerMenu$DynamicChestInventory.<init>(TinkerChestContainerMenu.java:31) ~[Hephaestus-1.20.1-3.6.3.232.jar:?]
	at slimeknights.tconstruct.tables.menu.TinkerChestContainerMenu.<init>(TinkerChestContainerMenu.java:18) ~[Hephaestus-1.20.1-3.6.3.232.jar:?]
	at slimeknights.tconstruct.tables.block.entity.chest.AbstractChestBlockEntity.createMenu(AbstractChestBlockEntity.java:54) ~[Hephaestus-1.20.1-3.6.3.232.jar:?]
	at io.github.fabricators_of_create.porting_lib.util.NetworkHooks.openScreen(NetworkHooks.java:58) ~[porting_lib_base-2.1.1139+1.20-ety-refactor-3dfdfdcf35b5fd79.jar:?]
	at io.github.fabricators_of_create.porting_lib.util.NetworkHooks.openScreen(NetworkHooks.java:39) ~[porting_lib_base-2.1.1139+1.20-ety-refactor-3dfdfdcf35b5fd79.jar:?]
	at slimeknights.mantle.block.InventoryBlock.openGui(InventoryBlock.java:48) ~[mantle-1.20.1-1.9.254-a9382e6bb8357e72.jar:?]
	at slimeknights.tconstruct.tables.block.TabbedTableBlock.openGui(TabbedTableBlock.java:16) ~[Hephaestus-1.20.1-3.6.3.232.jar:?]
	at slimeknights.mantle.block.InventoryBlock.method_9534(InventoryBlock.java:66) ~[mantle-1.20.1-1.9.254-a9382e6bb8357e72.jar:?]
	at slimeknights.tconstruct.tables.block.ChestBlock.method_9534(ChestBlock.java:95) ~[Hephaestus-1.20.1-3.6.3.232.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1140) ~[client-intermediary.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Crash Report

N/A

### Other mods

- Fabric API
- Hephaestus

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues

**Comment by AlphaMode** [comment]
Seems to be fixed in the latest version
